name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (7.4)
        uses: docker/build-push-action@v2
        with:
          context: ./php7.4-fpm
          file: ./php7.4-fpm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:7.4

      - name: Build and Push (8.1)
        uses: docker/build-push-action@v2
        with:
          context: ./php8.1-fpm
          file: ./php8.1-fpm/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:8.1